CREATE TABLE "092018B1"
               (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
               REG_NUM_A              VARCHAR,
               NUM_ACC_SEC_B          VARCHAR,
               INP_BAL_C              VARCHAR,
               INP_DRAG_MET_D         VARCHAR,
               INP_BAL_FINISH_E       VARCHAR,
               TURN_REP_DEBIT_F       VARCHAR,
               TURN_REP_DEB_DEPO_G    VARCHAR,
               TURN_REP_KREDIT_H      VARCHAR,
               TURN_REP_I             VARCHAR,
               TURN_REP_DRAG_MET_J    VARCHAR,
               TURN_REP_KRED_FINISH_K VARCHAR,
               OUT_BAL_L              VARCHAR,
               OUT_BAL_DRAG_MET_M     VARCHAR,
               OUT_BAL_FINISH_N       VARCHAR);
create table "092018N1"
                (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ORG_REG_ACC VARCHAR,
                ORG_NAME    VARCHAR);
create table   "NAMES" (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NUM_ACC_PLAN  VARCHAR,
                        NAME_ACC_PLAN VARCHAR);